export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  ROOM_ALREADY_EXISTS: "ROOM_ALREADY_EXISTS",
  ROOM_NOT_AVAILABLE: "ROOM_NOT_AVAILABLE",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",

  HOTEL_NOT_FOUND: "HOTEL_NOT_FOUND",

  INVALID_DATES: "INVALID_DATES",
  INVALID_CAPACITY: "INVALID_CAPACITY",

  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  ALREADY_CANCELLED: "ALREADY_CANCELLED",
  CANCELLATION_DEADLINE_PASSED: "CANCELLATION_DEADLINE_PASSED",
  ALREADY_REVIEWED: "ALREADY_REVIEWED",
  BOOKING_NOT_ELIGIBLE: "BOOKING_NOT_ELIGIBLE",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;
